/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CampaignRouteImport } from './routes/campaign'
import { Route as CardsRouteImport } from './routes/cards'
import { Route as CharacterRouteImport } from './routes/character'
import { Route as ProgressRouteImport } from './routes/progress'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as WorldRouteImport } from './routes/world'
import { Route as CardCardIdRouteImport } from './routes/card.$cardId'
import { Route as QuestAreaIdRouteImport } from './routes/quest.$areaId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CampaignRoute = CampaignRouteImport.update({
  id: '/campaign',
  path: '/campaign',
  getParentRoute: () => rootRouteImport,
} as any)
const CardsRoute = CardsRouteImport.update({
  id: '/cards',
  path: '/cards',
  getParentRoute: () => rootRouteImport,
} as any)
const CharacterRoute = CharacterRouteImport.update({
  id: '/character',
  path: '/character',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgressRoute = ProgressRouteImport.update({
  id: '/progress',
  path: '/progress',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const WorldRoute = WorldRouteImport.update({
  id: '/world',
  path: '/world',
  getParentRoute: () => rootRouteImport,
} as any)
const CardCardIdRoute = CardCardIdRouteImport.update({
  id: '/card/$cardId',
  path: '/card/$cardId',
  getParentRoute: () => rootRouteImport,
} as any)
const QuestAreaIdRoute = QuestAreaIdRouteImport.update({
  id: '/quest/$areaId',
  path: '/quest/$areaId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/campaign': typeof CampaignRoute
  '/cards': typeof CardsRoute
  '/character': typeof CharacterRoute
  '/progress': typeof ProgressRoute
  '/settings': typeof SettingsRoute
  '/world': typeof WorldRoute
  '/card/$cardId': typeof CardCardIdRoute
  '/quest/$areaId': typeof QuestAreaIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/campaign': typeof CampaignRoute
  '/cards': typeof CardsRoute
  '/character': typeof CharacterRoute
  '/progress': typeof ProgressRoute
  '/settings': typeof SettingsRoute
  '/world': typeof WorldRoute
  '/card/$cardId': typeof CardCardIdRoute
  '/quest/$areaId': typeof QuestAreaIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/campaign': typeof CampaignRoute
  '/cards': typeof CardsRoute
  '/character': typeof CharacterRoute
  '/progress': typeof ProgressRoute
  '/settings': typeof SettingsRoute
  '/world': typeof WorldRoute
  '/card/$cardId': typeof CardCardIdRoute
  '/quest/$areaId': typeof QuestAreaIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/campaign'
    | '/cards'
    | '/character'
    | '/progress'
    | '/settings'
    | '/world'
    | '/card/$cardId'
    | '/quest/$areaId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/campaign'
    | '/cards'
    | '/character'
    | '/progress'
    | '/settings'
    | '/world'
    | '/card/$cardId'
    | '/quest/$areaId'
  id:
    | '__root__'
    | '/'
    | '/campaign'
    | '/cards'
    | '/character'
    | '/progress'
    | '/settings'
    | '/world'
    | '/card/$cardId'
    | '/quest/$areaId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CampaignRoute: typeof CampaignRoute
  CardsRoute: typeof CardsRoute
  CharacterRoute: typeof CharacterRoute
  ProgressRoute: typeof ProgressRoute
  SettingsRoute: typeof SettingsRoute
  WorldRoute: typeof WorldRoute
  CardCardIdRoute: typeof CardCardIdRoute
  QuestAreaIdRoute: typeof QuestAreaIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campaign': {
      id: '/campaign'
      path: '/campaign'
      fullPath: '/campaign'
      preLoaderRoute: typeof CampaignRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cards': {
      id: '/cards'
      path: '/cards'
      fullPath: '/cards'
      preLoaderRoute: typeof CardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/character': {
      id: '/character'
      path: '/character'
      fullPath: '/character'
      preLoaderRoute: typeof CharacterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/progress': {
      id: '/progress'
      path: '/progress'
      fullPath: '/progress'
      preLoaderRoute: typeof ProgressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/world': {
      id: '/world'
      path: '/world'
      fullPath: '/world'
      preLoaderRoute: typeof WorldRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/card/$cardId': {
      id: '/card/$cardId'
      path: '/card/$cardId'
      fullPath: '/card/$cardId'
      preLoaderRoute: typeof CardCardIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quest/$areaId': {
      id: '/quest/$areaId'
      path: '/quest/$areaId'
      fullPath: '/quest/$areaId'
      preLoaderRoute: typeof QuestAreaIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CampaignRoute: CampaignRoute,
  CardsRoute: CardsRoute,
  CharacterRoute: CharacterRoute,
  ProgressRoute: ProgressRoute,
  SettingsRoute: SettingsRoute,
  WorldRoute: WorldRoute,
  CardCardIdRoute: CardCardIdRoute,
  QuestAreaIdRoute: QuestAreaIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
